version: '3'
services:
        spring-boot:
            build: .
            ports:
                - 8080:8080
            container_name: app
        prometheus:
            image: prom/prometheus
            ports:
                - 9090:9090
            volumes:
                - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            container_name: prometheus
            depends_on:
                - app
        grafana:
            image: grafana/grafana
            ports:
                - 3000:3000
            depends_on:
                - prometheus
            container_name: grafana