version: '3'
services:
        spring-boot:
            build: .
            ports:
                - 8080:8080
            container_name: app
        prometheus:
            image: prom/prometheus
            ports:
                - 9090:9090
            container_name: prometheus
            depends_on:
                - app
        grafana:
            image: grafana/grafana
            ports:
                - 2000:2000
            depends_on:
                - prometheus
            environment:
                - GF_SERVER_HTTP_PORT=2000
            container_name: grafana
            