{
 "title": "Monitor Springboot Statistics",
 "description": "Mockuai SpringBoot Monitor Statistics Template",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=~\"ec-messagecenter.*\"}, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(rocketmq_group_online{group=~\"GID-online-messagecenter_web.*\"},group)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(rocketmq_group_topic_rt{group=\"$group\"}, topic)"
    }
   },
   {
    "name": "rds_instance_name",
    "label": "rds_instance_name",
    "query": {
     "query": "label_values(aliyun_rds_cpu_usage{instance_name=~\"drds-trade.*\"}, instance_name)"
    }
   },
   {
    "name": "redis_instance_name",
    "label": "redis_instance_name",
    "query": {
     "query": "label_values(aliyun_redis_cpu_usage{instance_name=~\"robot.*\"}, instance_name)"
    }
   },
   {
    "name": "canal_instance",
    "label": "canal_instance",
    "query": {
     "query": "label_values(canal_instance{destination=~\".*item.*\"}, destination)"
    }
   },
   {
    "name": "es_instance",
    "label": "es_instance",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_number_of_nodes{instance=~\"finance.*\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "Connection Pool",
    "query": {
     "query": "label_values(druid_initial_size{application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"} * 100",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"} * 100",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "repeat": "memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Threads States",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "{{instance}} - {{state}}"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "repeat": "memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 7, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Dubbo Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(rpc_consumer_response_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "consumer: {{interfaceName}} [{{method}}] - {{status}}"
      },
      {
       "expr": "irate(rpc_provider_response_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "provider: {{interfaceName}} [{{method}}] - {{status}}"
      }
     ]
    },
    {
     "title": "Response Max Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rpc_consumer_response_seconds_max{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "consumer: {{interfaceName}} [{{method}}] - {{status}}"
      },
      {
       "expr": "rpc_provider_response_seconds_max{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "provider: {{interfaceName}} [{{method}}] - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Error Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_global_error_total{instance=\"$instance\", application=\"$application\"}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tomcat_sessions_active_current_sessions{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "active sessions"
      }
     ]
    },
    {
     "title": "Sent & Recieved Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(tomcat_global_sent_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Sent Bytes"
      },
      {
       "expr": "irate(tomcat_global_received_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Recieved Bytes"
      }
     ]
    },
    {
     "title": "Thread Config Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_threads_config_max_threads{instance=\"$instance\", application=\"$application\"}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_current_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Current thread"
      },
      {
       "expr": "tomcat_threads_busy_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Current thread busy"
      }
     ]
    },
    {
     "title": "TCP DROPS",
     "type": "graph",
     "description": "监听队列连接丢弃数",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$instance\"}[5m])"
      }
     ]
    },
    {
     "title": "TCP OVDERFLOW",
     "type": "graph",
     "description": "监听 socket 的队列溢出",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=\"$instance\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid-Client Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Initial Pool Size",
     "type": "stat",
     "description": "连接池建立时创建的初始化连接数",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(druid_initial_size{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})",
       "legendFormat": "Initial Size"
      }
     ]
    },
    {
     "title": "Min Idle Connections",
     "type": "stat",
     "description": "连接池中最小的活跃连接数",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(druid_min_idle{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})",
       "legendFormat": "Min Idle"
      }
     ]
    },
    {
     "title": "Max Active Connections",
     "type": "stat",
     "description": "连接池中最大的活跃连接数",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(druid_max_active{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
      }
     ]
    },
    {
     "title": "Peak Pooling Connections",
     "type": "stat",
     "description": "连接池中连接数的峰值",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(druid_pooling_peak{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
      }
     ]
    },
    {
     "title": "Peak Active Connections",
     "type": "stat",
     "description": "活跃连接数峰值",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(druid_active_peak{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
      }
     ]
    },
    {
     "title": "Wait Thread Connections",
     "type": "stat",
     "description": "等待获取连接的线程数",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(druid_wait_thread_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
      }
     ]
    },
    {
     "title": "Pooling Connections",
     "type": "graph",
     "description": "当前连接池中空闲的连接数",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "druid_pooling_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "description": "当前连接池中活跃的连接数 ",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "druid_active_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Logic Connect",
     "type": "graph",
     "description": "在过去的1分钟以内，产生的逻辑连接数",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_logic_connect_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Logic Connect - Error",
     "type": "graph",
     "description": "在过去的1分钟以内，出错的逻辑连接数",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_logic_connect_error_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Physical Connect - Error",
     "type": "graph",
     "description": "在过去的1分钟以内，物理连接失败数",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_physical_connect_error_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Not Empty Wait count",
     "type": "graph",
     "description": "在过去的1分钟以内，获取连接最多等待的次数",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_not_empty_wait_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Not Empty Wait Latency",
     "type": "graph",
     "description": "在过去的两分钟以内，获取连接产生的延时",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(druid_not_empty_wait_millis{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m]) / rate(druid_not_empty_wait_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "SQL Execution Rate",
     "type": "graph",
     "description": "在过去的两分钟以内，“SQL执行”的每秒速率",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(druid_execute_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Start Transaction Rate",
     "type": "graph",
     "description": "在过去的两分钟以内，“发起事务”的每秒速率",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(druid_start_transaction_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Commit Transaction Rate",
     "type": "graph",
     "description": "在过去的两分钟以内，“事务提交”的每秒速率",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(druid_commit_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Roolback Transaction Rate",
     "type": "graph",
     "description": "在过去的两分钟以内，“事务回滚”的每秒速率",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(druid_rollback_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "SQL Execution Error",
     "type": "graph",
     "description": "在过去的两分钟以内，“SQL执行失败”的每秒速率",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(druid_error_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis-Client Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Total",
     "type": "stat",
     "description": "资源池中的最大连接数，默认值: 8",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "redis_max_total{application=\"$application\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Min Idle",
     "type": "stat",
     "description": "资源池确保的最少空闲连接数，默认值: 0",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "redis_min_idle{application=\"$application\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Idle",
     "type": "stat",
     "description": "资源池允许的最大空闲连接数，默认值: 8",
     "gridPos": { "h": 2, "w": 5, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "redis_max_idle{application=\"$application\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Block When Exhausted",
     "type": "stat",
     "description": "当资源池用尽后，调用者是否要等待。只有当值为true时，下面的maxWaitMillis才会生效。建议使用默认值。",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "redis_block_when_exhausted{application=\"$application\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Wait Millis",
     "type": "stat",
     "description": "当资源池连接用尽后，调用者的最大等待时间，单位是毫秒，默认值: -1, 建议设置合理的值",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(redis_max_wait_millis{application=\"$application\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Test While idle",
     "type": "stat",
     "description": "是否开启空闲资源检测。默认值：false。建议：true",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(redis_test_while_idle{application=\"$application\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Min Evictable Idle Time Millis",
     "type": "stat",
     "description": "资源池中资源的最小空闲时间（单位为毫秒），达到此值后空闲资源将被移除。默认值：180000（即30分钟）；可根据自身业务决定，一般默认值即可",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(redis_min_evictable_idle_time_millis{application=\"$application\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Num Test Per Eviction_run",
     "type": "stat",
     "description": "做空闲资源检测时，每次检测资源的个数。默认值：3；可根据自身应用连接数进行微调，如果设置为 -1，就是对所有连接做空闲监测",
     "gridPos": { "h": 2, "w": 5, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(redis_num_tests_per_eviction_run{application=\"$application\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Soft Min Evictable Idle Time Millis",
     "type": "stat",
     "description": "资源池中资源最小空闲时间，单位为毫秒，默认值: 30分钟，当达到该值后空闲资源将被移除，建议根据业务自身设定",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "redis_soft_min_evictable_idle_time_millis{application=\"$application\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Time Between Eviction Runs Millis",
     "type": "stat",
     "description": "空闲资源的检测周期（单位为毫秒）,默认值: -1（不检测）;建议设置，周期自行选择",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(redis_timeBetween_eviction_runs_millis{application=\"$application\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Num Waiters",
     "type": "graph",
     "description": "等待获取连接的数量",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_num_waiters{application=~\"$application\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Num Idle",
     "type": "graph",
     "description": "当前连接池中空闲的连接数",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_num_idle{application=\"$application\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Active Num",
     "type": "graph",
     "description": "当前活跃的连接数",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_active_num{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Log4j Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Rocketmq Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "GROUP-大于0表示订阅关系不一致",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group) (rocketmq_group_subscription_same{group=\"$group\"})",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "GROUP-大于0表示不在线",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group) (rocketmq_group_online{group=\"$group\"})",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "GROUP-近1小时死信队列（大于0表示存在）",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group) (rocketmq_group_dead_letter_queue{group=\"$group\"})",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "GROUP-大于0表示rebalance异常",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group) (rocketmq_group_rebalanceOK{group=\"$group\"})",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "GROUP-实时消费速度",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group) (rocketmq_group_tps{group=\"$group\"})",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "GROUP-实时消息堆积量",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 7, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group) (rocketmq_group_total_diff{group=\"$group\"})",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "GROUP-消息延迟时间",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group) (rocketmq_group_delay_time{group=\"$group\"}) / 1000",
       "legendFormat": "通知配置：{{group}}"
      }
     ]
    },
    {
     "title": "GROUP_TOPIC 消费 RT 时间",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group,topic) (rocketmq_group_topic_rt{group=\"$group\",topic=\"$topic\"})",
       "legendFormat": "{{group}} : {{topic}}"
      }
     ]
    },
    {
     "title": "GROUP_TOPIC 实时消息堆积量",
     "type": "graph",
     "description": "消费tps",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group,topic) (rocketmq_group_topic_total_diff{group=\"$group\",topic=\"$topic\"})",
       "legendFormat": "{{group}} : {{topic}}"
      }
     ]
    },
    {
     "title": "GROUP_TOPIC 实时消费成功数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group,topic) (rocketmq_group_topic_ok_tps{group=\"$group\",topic=\"$topic\"})",
       "legendFormat": "{{group}} : {{topic}}"
      }
     ]
    },
    {
     "title": "GROUP_TOPIC 实时消费失败数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (group,topic) (rocketmq_group_topic_failed_tps{group=\"$group\",topic=\"$group\"})",
       "legendFormat": "{{group}} : {{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sentinel Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pass QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (application)(irate(sentinel_pass_request_total{application=\"$application\"}[1m]))",
       "legendFormat": "{{application}}"
      }
     ]
    },
    {
     "title": "Total Block QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (application)((irate(sentinel_block_request_total{application=\"$application\"}[1m])))",
       "legendFormat": "{{application}}"
      }
     ]
    },
    {
     "title": "Total Pass Success QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (application)(irate(sentinel_success_request_total{application=\"$application\"}[1m])))",
       "legendFormat": "{{application}}"
      }
     ]
    },
    {
     "title": "Total Pass Block QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (application)(irate(sentinel_exception_request_total{application=\"$application\"}[1m]))",
       "legendFormat": "{{application}}"
      }
     ]
    },
    {
     "title": "Resource Pass QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (resource)(increase(sentinel_pass_request_total{application=\"$application\"}[1m]))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Resource Exception QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (resource)(irate(sentinel_exception_request_total{application=\"$application\"}[1m]))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Resource Block QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (resource)(irate(sentinel_block_request_total{application=\"$application\"}[1m]))",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDS Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "rds_instance_name",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (instance_name) (aliyun_rds_cpu_usage{instance_name=\"$rds_instance_name\"})"
      }
     ]
    },
    {
     "title": "Mem Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (instance_name) (aliyun_rds_mem_usage{instance_name=\"$rds_instance_name\"})"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (instance_name) (aliyun_rds_tps{instance_name=\"$rds_instance_name\"})"
      }
     ]
    },
    {
     "title": "IOPS Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (instance_name) (aliyun_rds_iops_usage{instance_name=\"$rds_instance_name\"})"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aliyun_rds_active_session{instance_name=~\"$rds_instance_name\"}",
       "legendFormat": "{{instance_name}}_活跃连接数"
      },
      {
       "expr": "aliyun_rds_total_session{instance_name=~\"$rds_instance_name\"}",
       "legendFormat": "{{instance_name}}_总连接数"
      }
     ]
    },
    {
     "title": "Disk_Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "aliyun_rds_disk_usage{instance_name=~\"$rds_instance_name\"}",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "slave_lag",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aliyun_rds_slave_lag{instance_name=~\"$rds_instance_name\"}",
       "legendFormat": "{{instance_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "redis_instance_name",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (instance_name) (aliyun_redis_cpu_usage{instance_name=\"$redis_instance_name\"})"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (instance_name) (aliyun_redis_memory_usage{instance_name=\"$redis_instance_name\"})"
      }
     ]
    },
    {
     "title": "Intranet Out Ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (instance_name) (aliyun_redis_intranet_out_ratio{instance_name=\"$redis_instance_name\"})"
      }
     ]
    },
    {
     "title": "rt",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aliyun_redis_avg_rt{instance_name=~\"$redis_instance_name\"}",
       "legendFormat": "{{instance_name}}_avg"
      },
      {
       "expr": "aliyun_redis_max_rt{instance_name=~\"$redis_instance_name\"}",
       "legendFormat": "{{instance_name}}_max"
      }
     ]
    },
    {
     "title": "GET/PUT QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aliyun_redis_get_qps{instance_name=~\"$redis_instance_name\"}",
       "legendFormat": "{{instance_name}}_get"
      },
      {
       "expr": "aliyun_redis_put_qps{instance_name=~\"$redis_instance_name\"}",
       "legendFormat": "{{instance_name}}_put"
      }
     ]
    },
    {
     "title": "出入口带宽使用率",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "aliyun_redis_intranet_out_ratio{instance_name=~\"$redis_instance_name\"}",
       "legendFormat": "{{instance_name}}_out"
      },
      {
       "expr": "aliyun_redis_intranet_in_ratio{instance_name=~\"$redis_instance_name\"}",
       "legendFormat": "{{instance_name}}_in"
      }
     ]
    }
   ]
  },
  {
   "title": "Canal Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "canal_instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Basic",
     "type": "graph",
     "description": "Canal instance 基本信息。",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "canal_instance{destination=~\"$canal_instance\"}",
       "legendFormat": "Destination: {{destination}}"
      },
      {
       "expr": "canal_instance_parser_mode{destination=~\"$canal_instance\"}",
       "legendFormat": "Parallel parser: {{parallel}}"
      },
      {
       "expr": "canal_instance_store{destination=~\"$canal_instance\"}",
       "legendFormat": "Batch mode: {{batchMode}}"
      },
      {
       "expr": "canal_instance_store{destination=~\"$canal_instance\"}",
       "legendFormat": "Buffer size: {{size}}"
      }
     ]
    },
    {
     "title": "Network bandwith",
     "type": "graph",
     "description": "Canal instance 网络带宽占用。  \ninbound: 记录instance接收binlog字节数。 \noutbound: 记录向instance client发送数据包字节数。",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "rate(canal_instance_received_binlog_bytes{destination=~\"$canal_instance\", parser=\"0\"}[2m]) / 1024",
       "legendFormat": "inbound"
      },
      {
       "expr": "rate(canal_instance_client_bytes{destination=~\"$canal_instance\"}[2m]) / 1024",
       "legendFormat": "outbound"
      }
     ]
    },
    {
     "title": "Delay",
     "type": "graph",
     "description": "master: 记录server与MySQL master的延时。  \nput: store put操作的时间点为基准。  \nget: client get操作的时间点为基准。  \nack:  client ack操作的时间点为基准。  ",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "canal_instance_traffic_delay{destination=~\"$canal_instance\"} / 1000",
       "legendFormat": "master"
      },
      {
       "expr": "canal_instance_put_delay{destination=~\"$canal_instance\"} / 1000",
       "legendFormat": "put"
      },
      {
       "expr": "canal_instance_get_delay{destination=~\"$canal_instance\"} / 1000",
       "legendFormat": "get"
      },
      {
       "expr": "canal_instance_ack_delay{destination=~\"$canal_instance\"} / 1000",
       "legendFormat": "ack"
      }
     ]
    },
    {
     "title": "Blocking",
     "type": "graph",
     "description": "dump：记录instance dump线程提交到异步解析队列过程中的阻塞时间(仅parallel解析模式)。  \nsink：记录instance sink线程put数据至store的阻塞时间 \n",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "clamp_max(rate(canal_instance_publish_blocking_time{destination=~\"$canal_instance\", parser=\"0\"}[2m]), 1000) / 10",
       "legendFormat": "dump"
      },
      {
       "expr": "clamp_max(rate(canal_instance_sink_blocking_time{destination=~\"$canal_instance\"}[2m]), 1000) / 10",
       "legendFormat": "sink"
      }
     ]
    },
    {
     "title": "Client requests",
     "type": "graph",
     "description": "记录instance client请求次数的计数。",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(canal_instance_client_packets{destination=~\"$canal_instance\"}[5m])",
       "legendFormat": "{{packetType}}"
      }
     ]
    },
    {
     "title": "Client QPS",
     "type": "graph",
     "description": "GET：记录instance client请求GET QPS。  \nACK：记录instance client请求ACK QPS。  ",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(canal_instance_client_packets{destination=~\"$canal_instance\",packetType=\"GET\"}[2m])",
       "legendFormat": "GET"
      },
      {
       "expr": "rate(canal_instance_client_packets{destination=~\"$canal_instance\",packetType=\"CLIENTACK\"}[2m])",
       "legendFormat": "ACK"
      }
     ]
    },
    {
     "title": "Empty packets",
     "type": "graph",
     "description": "empty：记录向instance client发送get接口的空结果的计数。",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(canal_instance_client_empty_batches{destination=~\"$canal_instance\"}[2m])",
       "legendFormat": "empty"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "graph",
     "description": "记录instance client请求的响应时间概况",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(canal_instance_client_request_latency_bucket{destination=~\"$canal_instance\"}[2m])",
       "legendFormat": "{{le}}ms"
      }
     ]
    },
    {
     "title": "Store remain events",
     "type": "graph",
     "description": "Canal instance ringbuffer内未释放的events数量。",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "canal_instance_store_produce_seq{destination=~\"$canal_instance\"} - canal_instance_store_consume_seq{destination=~\"$canal_instance\"}",
       "legendFormat": "events"
      }
     ]
    },
    {
     "title": "Store remain mem",
     "type": "graph",
     "description": "Canal instance ringbuffer 内未释放events占用内存。",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "(canal_instance_store_produce_mem{destination=~\"$canal_instance\"} - canal_instance_store_consume_mem{destination=~\"$canal_instance\"}) / 1024",
       "legendFormat": "memsize"
      }
     ]
    },
    {
     "title": "TPS(table rows)",
     "type": "graph",
     "description": "put: 记录instance的store put操作完成的table rows。  \nget: 记录instance的client get请求返回的table rows。  \nack: 记录instance的client ack操作释放的table rows。  ",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(canal_instance_put_rows{destination=~\"$canal_instance\"}[2m])",
       "legendFormat": "put"
      },
      {
       "expr": "rate(canal_instance_get_rows{destination=~\"$canal_instance\"}[2m])",
       "legendFormat": "get"
      },
      {
       "expr": "rate(canal_instance_ack_rows{destination=~\"$canal_instance\"}[2m])",
       "legendFormat": "ack"
      }
     ]
    },
    {
     "title": "TPS(MySQL transaction)",
     "type": "graph",
     "description": "记录instance接收transactions的个数。",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(canal_instance_transactions{destination=~\"$canal_instance\"}[2m])",
       "legendFormat": "transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "ES Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "es_instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (color) (elasticsearch_cluster_health_status{instance=\"$es_instance\"}) "
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(elasticsearch_jvm_memory_used_bytes{area=\"heap\",instance=\"$es_instance\"} / elasticsearch_jvm_memory_max_bytes{area=\"heap\",instance=\"$es_instance\"}) * 100\n"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_process_cpu_percent{instance=\"$es_instance\"}"
      }
     ]
    },
    {
     "title": "Filesystem Data Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(1-(elasticsearch_filesystem_data_available_bytes{instance=\"$es_instance\"} / elasticsearch_filesystem_data_size_bytes{instance=\"$es_instance\"})) * 100\n"
      }
     ]
    }
   ]
  }
 ]
}